<?php

/**
 * @file
 * Main file of Chanchal Test module.
 */

/**
 * Implements hook_block_info().
 */
function bite_me_block_info() {
  $blocks = array();

  $blocks['bite_me'] = array(
    'info' => t('Bite Me by Chanchal'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function bite_me_block_view($delta = '') {

switch($delta) {
    case 'bite_me':
      $block['subject'] = t('Bite Me'); // Most forms don't have a subject 
      $block['content'] = drupal_get_form('bite_me_form');
      break;
   }
   return $block;
 }

/**
 * hook_form implementation
 */
function bite_me_form($node, &$form_state){

 $form = array();

$form['title'] = array(
 '#type' => 'textfield',
 '#title' => t('Name'),
 '#size' => 18,
 '#maxlength' => 50,
 '#required' => TRUE,
);

$form['personalinfo']['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#required' => TRUE,
    '#default_value' => "",
    '#description' => "Please enter your email.",
    '#size' => 18,
    '#maxlength' => 60,
    '#element_validate' => array('bite_me_email_element_validate'),
);


$form['keywords'] = array(
 '#type' => 'textarea',
 '#title' => t('Message'),
 
);



$form['selectbox'] = array(
    '#type' => 'select',
    '#title' => t('Select box'),
    '#options' => array(
      1 => 'Option A',
      2 => 'Option B',
      3 => 'Option C',
    ),
    '#description' => t('Choose an option.'),
  );

$form['submit'] = array(
	'#type' => 'submit', 
	'#value' => t('SUBMIT')
);


 return $form;
}

function bite_me_email_element_validate($element, &$form_state, $form) {
   if (!valid_email_address($element['#value'])) {
     form_error($element, t('Please enter a valid email address.'));
   }
}


